// Generated by CoffeeScript 1.6.2
(function() {
  var api, app, express, routes;

  express = require('express');

  routes = require('./routes');

  api = require('./routes/api');

  app = module.exports = express.createServer();

  app.configure(function() {
    app.set('views', "" + __dirname + "/views");
    app.set('view engine', 'jade');
    app.set('view options', {
      layout: false
    });
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express["static"]("" + __dirname + "/public"));
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get("/" + routes.index);

  app.get('/partials/:name', routes.partials);

  app.get('/api/posts', api.posts);

  app.get('/api/post/:id', api.post);

  app.post('/api/post', api.addPost);

  app.put('/api/post/:id', api.editPost);

  app["delete"]('/api/post/:id', api.deletePost);

  app.get('*', routes.index);

  app.listen(3000, function() {
    return console.log("Express server listening on port " + (app.address().port) + " in " + app.settings.env + " mode");
  });

}).call(this);
